In [1]:
import sys
print(sys.version)

3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)]


## 1.1 Importing libraries

Check that the libraries are installed correctly by running the following import statements

In [2]:
import gym
print(gym.__version__)

import os
os.environ['KERAS_BACKEND'] = 'theano'

import keras
print(keras.__version__)

0.17.2
2.4.3


In [3]:
import random
import math
import numpy as np
from collections import deque

## 1.2 OpenAI Gym Environment

The following cells build the 'CartPole-v0' environment that we will use in this project and runs it for twenty episodes.  

In [4]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[-0.00871801  0.0360481   0.04469148  0.01474214]
[-0.00799705  0.23050157  0.04498632 -0.26351191]
[-0.00338702  0.42495349  0.03971609 -0.54167318]
[ 0.00511205  0.61949538  0.02888262 -0.82158243]
[ 0.01750196  0.42399039  0.01245097 -0.51995694]
[ 0.02598177  0.61893487  0.00205183 -0.8086905 ]
[ 0.03836047  0.42378486 -0.01412198 -0.51536287]
[ 0.04683616  0.2288646  -0.02442923 -0.22716335]
[ 0.05141346  0.03410013 -0.0289725   0.0577147 ]
[ 0.05209546 -0.16059469 -0.02781821  0.34111764]
[ 0.04888356  0.03491179 -0.02099585  0.03979389]
[ 0.0495818  -0.15990289 -0.02019998  0.32577917]
[ 0.04638374 -0.3547315  -0.01368439  0.61202407]
[ 0.03928911 -0.15942099 -0.00144391  0.31506266]
[ 0.03610069 -0.35452235  0.00485734  0.60728988]
[ 0.02901025 -0.15946865  0.01700314  0.31614083]
[0.02582087 0.03540704 0.02332596 0.02886824]
[ 0.02652901  0.23018685  0.02390332 -0.25636478]
[0.03113275 0.03473192 0.01877603 0.04376076]
[ 0.03182739  0.22957967  0.01965124 -0.24293952]
[0.03641

[-0.03475504 -0.00633327  0.09027475  0.13051291]
[-0.0348817   0.18738733  0.092885   -0.13238   ]
[-0.03113395  0.38106449  0.0902374  -0.39437448]
[-0.02351266  0.57479788  0.08234992 -0.6572984 ]
[-0.01201671  0.76868283  0.06920395 -0.92295674]
[ 0.00335695  0.96280501  0.05074481 -1.1931133 ]
[ 0.02261305  1.15723429  0.02688255 -1.46946924]
[ 0.04575774  0.96179395 -0.00250684 -1.16851213]
[ 0.06499361  0.7667047  -0.02587708 -0.87661619]
[ 0.08032771  0.96216863 -0.0434094  -1.17732093]
[ 0.09957108  1.15782671 -0.06695582 -1.48328993]
[ 0.12272762  0.96358215 -0.09662162 -1.21224626]
[ 0.14199926  1.15980925 -0.12086655 -1.53357661]
[ 0.16519544  0.96633302 -0.15153808 -1.28092783]
[ 0.1845221   1.16302551 -0.17715664 -1.61696731]
Episode finished after 31 timesteps
[-3.37336960e-02 -1.54919097e-02  2.54991487e-02 -8.36730320e-05]
[-0.03404353  0.17925524  0.02549748 -0.2846135 ]
[-0.03045843  0.37400443  0.01980521 -0.56914689]
[-0.02297834  0.56884309  0.00842227 -0.85552521

[ 0.11559392  0.57451487 -0.13597081 -1.02751004]
[ 0.12708422  0.77115889 -0.15652101 -1.35960595]
[ 0.1425074   0.57830697 -0.18371313 -1.11969382]
[ 0.15407354  0.38600698 -0.206107   -0.88980618]
Episode finished after 19 timesteps
[ 0.02815174 -0.00622937  0.01036609 -0.02640929]
[ 0.02802716  0.1887424   0.0098379  -0.31580366]
[ 0.031802    0.38372285  0.00352183 -0.60536788]
[ 0.03947646  0.18855183 -0.00858553 -0.31157775]
[ 0.0432475  -0.00644676 -0.01481708 -0.02161476]
[ 0.04311856 -0.20135312 -0.01524938  0.26635663]
[ 0.0390915  -0.00601688 -0.00992225 -0.03109681]
[ 0.03897116 -0.20099515 -0.01054418  0.2584391 ]
[ 0.03495126 -0.39596499 -0.0053754   0.54777768]
[ 0.02703196 -0.20076794  0.00558015  0.25340597]
[ 0.0230166  -0.39596912  0.01064827  0.54784374]
[ 0.01509722 -0.20099837  0.02160515  0.25853473]
[ 0.01107725 -0.39642199  0.02677584  0.55795317]
[ 0.00314881 -0.20168595  0.03793491  0.27382496]
[-0.00088491 -0.00712522  0.0434114  -0.00665599]
[-0.00102741 -

To better understand the environment, lets take a look at the possible actions and observations for the `CartPole-v0` environment.  

In [5]:
print(env.action_space)
print(env.observation_space)

Discrete(2)
Box(4,)


The Discrete() space allows a fixed range of non-negative numbers.  In this case, valid actions are either 0 or 1.  The Box space represents an n-dimensional box.  Valid observations for this case will be an array of four numbers. We can also check the Box's bounds:

In [6]:
print(env.observation_space.high)
print(env.observation_space.low)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


## 2. Define Parameters

In [7]:
# Training parameters
n_episodes = 1000
n_win_ticks = 195
max_env_steps = None

gamma = 1.0 # discount factor
epsilon = 1.0 # exploration
epsilon_min = 0.01
epsilon_decay = 0.995
alpha = 0.01 # the learning rate
alpha_decay = 0.01

batch_size = 64
monitor = False
quiet = False

# Environment parameters
memory = deque(maxlen = 100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None: env.max_episode_steps = max_env_steps

## 2.1 Building the Neural Network

The following cells define the model we will be using.

In [8]:
# Building the neural network

from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Model definition
model = Sequential()
model.add(Dense(24, input_dim = 4, activation = 'relu'))
model.add(Dense(48, activation = 'relu'))
model.add(Dense(2, activation = 'relu'))
model.compile(loss = 'mse', optimizer = Adam(lr = alpha, decay = alpha_decay))

## 2.2 Defining Necessary Functions

It is best practice to define common operations as functions.  The following operations will be used often, so we define a function for each.

In [9]:
# Defining necessary fuctions

def remember(state, action, reward, next_state, done):
    memory.append(state, action, reward, next_state, done)
    
def choose_action(state, epsilon):
    return env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(model.predct(state))

def get_epsilon(t):
    return max(epsilon_min, min(epsilon, 1.0 - math.log10((t + 1) * epsilon_decay)))

def preprocess_state(state):
    return np.reshape(state, [1, 4])

def replay(batch_size, epsilon):
    x_batch, y_batch = [], []
    minibatch = random.sample(memory, min(len(memory), batch_size))
    
    for state, action, reward, next_state, done in minibatch:
        y_target = model.predict(state)
        y_target[0][action] = reward if done else reward + gamma * np.max(model.predict(next_state)[0])
        x_batch.append(state[0])
        y_batch.append(y_target[0])
    model.fit(np.array(x_batch), np.array(y_batch), batch_size = len(x_batch), verbose = 0)
    
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay

## 3. Defining Run Function

Lets define a function, `run()` that records the environment state and uses our network to choose the best action.  

In [10]:
# Define run function
def run():
    scores = deque(maxlen = 100)

    for e in range(n_episodes):
        state = preprocess_state(env.reset())
        done = False
        i = 0
        while not done:
            action = choose_action(state, get_epsilon(e))
            next_state, reward, done, _ = env.step(action)
            env.render()
            next_state = preprocess_state(next_state)
            remember(state, action, reward, next_state, done)
            state = next_state
            i += 1

        scores.append(i)
        mean_score = np.mean(scores)
        if mean_score >= n_win_ticks and e >= 100:
            if not quiet: print('Ran {} episodes. Solved after {} trials'.format(e, e - 100))
            return e - 100
        if e % 100 == 0 and not quiet:
            print('[Episode {}] - Mean survival time over last 100 episodes was {} ticks.'.format(e, mean_score))
   
        replay(batch_size, epsilon)

    if not quiet: print('Did not solve after {} episodes'.format(e))
    return e

## 4. Train the Network!

Here is the complete code together. Because Jupyter runs on a kernel, this code will work best if a single cell is used to run the entire code.

In [ ]:
# Training the network
import random
import gym
import math
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Training Parameters
n_episodes=1000
n_win_ticks=195
max_env_steps=None
gamma=1.0
epsilon=1.0
epsilon_min=0.01
epsilon_decay=0.995
alpha=0.01
alpha_decay=0.01
batch_size=64
monitor=False
quiet=False

# Environment Parameters
memory = deque(maxlen=100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None: env.max_episode_steps = max_env_steps

from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Model Definition
model = Sequential()
model.add(Dense(24, input_dim=4, activation='relu'))
model.add(Dense(48, activation='relu'))
model.add(Dense(2, activation='relu'))
model.compile(loss='mse', optimizer=Adam(lr=alpha, decay=alpha_decay))

def remember(state, action, reward, next_state, done):
    memory.append((state, action, reward, next_state, done))

def choose_action(state, epsilon):
    return env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(
        model.predict(state))

def get_epsilon(t):
    return max(epsilon_min, min(epsilon, 1.0 - math.log10((t + 1) * epsilon_decay)))

def preprocess_state(state):
    return np.reshape(state, [1, 4])

def replay(batch_size, epsilon):
    x_batch, y_batch = [], []
    minibatch = random.sample(
        memory, min(len(memory), batch_size))
    for state, action, reward, next_state, done in minibatch:
        y_target = model.predict(state)
        y_target[0][action] = reward if done else reward + gamma * np.max(model.predict(next_state)[0])
        x_batch.append(state[0])
        y_batch.append(y_target[0])

    model.fit(np.array(x_batch), np.array(y_batch), batch_size=len(x_batch), verbose=0)
    
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay    
        
def run():
    scores = deque(maxlen=100)

    for e in range(n_episodes):
        state = preprocess_state(env.reset())
        done = False
        i = 0
        while not done:
            action = choose_action(state, get_epsilon(e))
            next_state, reward, done, _ = env.step(action)
            env.render()
            next_state = preprocess_state(next_state)
            remember(state, action, reward, next_state, done)
            state = next_state
            i += 1

        scores.append(i)
        mean_score = np.mean(scores)
        if mean_score >= n_win_ticks and e >= 100:
            if not quiet: print('Ran {} episodes. Solved after {} trials'.format(e, e - 100))
            return e - 100
        if e % 20 == 0 and not quiet:
            print('[Episode {}] - Mean survival time over last 100 episodes was {} ticks.'.format(e, mean_score))
   
        replay(batch_size, get_epsilon(e))

    if not quiet: print('Did not solve after {} episodes'.format(e))
    return e

run()

[Episode 0] - Mean survival time over last 100 episodes was 15.0 ticks.
